version: '2'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./docker/nginx/conf:/etc/nginx
      - ./www:/var/www
  php-fpm:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www

  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=zisu
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    build: ./docker/redis
    volumes:
      - ./data/redis:/data
      - ./docker/redis/redis.conf:/etc/redis/redis.conf

